### ISSUE TITLE
Step function

### ISSUE THREAD

**Issue by mrquincle** [grinsted/gwmcmc#4]
I liked how you picked up on the constraints.

Do you have some ideas about a custom step function? The current step assumes continuous random variables. If some random variables are discrete, or if they are membership functions, it might be convenient to provide for an user-defined step function.

Is that a nice idea?

**Comment by grinsted** [comment]
It would be nice. But, I am not sure how to implement this while not violating the assumptions in the Goodman and Weare sampler. Do you have a concrete idea for how it could be implemented i could look at.
