### ISSUE TITLE
Q: inference with bounded variables

### ISSUE THREAD

**Issue by drbenvincent** [grinsted/gwmcmc#5]
Great job on this. Does this algorithm allow for variables with a bounded range, say between 0-1. If so, is this implemented through a prior with zero values outside of this range?
Thanks.

**Comment by grinsted** [comment]
Yes, you have to implement it as a prior. In this  example the kinkpoint is constrained to be inside the observational period by the prior:
https://github.com/grinsted/gwmcmc/blob/master/html/ex_breakfit.md
