### ISSUE TITLE
Bracket for name value parameters?

### ISSUE THREAD

**Issue by benlansdell** [grinsted/gwmcmc#6]
In gwmcmc.m

17: %  [models,logP]=gwmcmc(minit,logPfuns,mccount,[Parameter,Value,Parameter,Value]);

Aren't the brackets a bit confusing, given the syntax is really:

[models,logP]=gwmcmc(minit, logPfuns, mccount, Parameter,Value, ...);

??

**Comment by grinsted** [comment]
I never considered it. My intended meaning is to show that the these arguments are optional. Maybe that  is clear even without brackets.
